version: 2

models:
  - name: fct_stock_performance
    description: "Daily performance metrics ανά symbol"
    columns:
      - name: symbol
        tests:
          - not_null
      - name: date
        tests:
          - not_null
      - name: close
        tests:
          - not_null
          # expression_is_true: οποιαδήποτε SQL έκφραση
          # αποτυγχάνει αν η έκφραση είναι FALSE
          - dbt_utils.expression_is_true:
              expression: "> 0"
      - name: volume
        tests:
          - dbt_utils.expression_is_true:
              expression: "> 0"

  - name: dim_symbol_stats
    description: "Aggregate statistics ανά symbol"
    columns:
      - name: symbol
        tests:
          - not_null
          - unique
          # Μόνο τα 5 symbols που έχουμε
          
      - name: total_days
        tests:
          - dbt_utils.expression_is_true:
              expression: "> 0"
      - name: volatility
        tests:
          - not_null